# Generated by Django 4.1.1 on 2022-10-08 12:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='Branch_name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='First_name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='Last_name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='Post',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='image',
        ),
        migrations.AddField(
            model_name='candidate',
            name='div',
            field=models.CharField(choices=[('A', 'COMPS A'), ('B', 'COMPS B')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='email_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
