# Generated by Django 4.1.1 on 2022-10-08 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Registered',
        ),
    ]
