# Generated by Django 4.1.1 on 2022-10-08 13:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_bcandidate_rename_candidate_acandidate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADivCandidate',
            fields=[
                ('name', models.CharField(max_length=200, null=True)),
                ('email_id', models.CharField(blank=True, max_length=50, null=True)),
                ('div', models.CharField(choices=[('A', 'COMPS A')], max_length=2, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ADivRegistration',
            fields=[
                ('name', models.CharField(max_length=200, null=True)),
                ('email_id', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('div', models.CharField(choices=[('A', 'COMPS A')], max_length=2, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BDivCandidate',
            fields=[
                ('name', models.CharField(max_length=200, null=True)),
                ('email_id', models.CharField(blank=True, max_length=50, null=True)),
                ('div', models.CharField(choices=[('B', 'COMPS B')], max_length=2, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BDivRegistration',
            fields=[
                ('name', models.CharField(max_length=200, null=True)),
                ('email_id', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('div', models.CharField(choices=[('B', 'COMPS B')], max_length=2, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ACandidate',
        ),
        migrations.DeleteModel(
            name='BCandidate',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
