# Generated by Django 4.1.1 on 2022-10-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_alter_adivcandidate_div_alter_adivcandidate_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adivcandidate',
            name='roll_no',
            field=models.IntegerField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='adivregistration',
            name='roll_no',
            field=models.IntegerField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='bdivcandidate',
            name='roll_no',
            field=models.IntegerField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='bdivregistration',
            name='roll_no',
            field=models.IntegerField(max_length=2, null=True),
        ),
    ]
