# Generated by Django 4.1.1 on 2022-10-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_adivcandidate_roll_no_adivregistration_roll_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adivcandidate',
            name='roll_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='adivregistration',
            name='roll_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bdivcandidate',
            name='roll_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bdivregistration',
            name='roll_no',
            field=models.IntegerField(null=True),
        ),
    ]
