# Generated by Django 4.1.1 on 2022-10-08 19:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0009_alter_adivcandidate_roll_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adivcandidate',
            name='roll_no',
        ),
        migrations.RemoveField(
            model_name='adivregistration',
            name='roll_no',
        ),
        migrations.RemoveField(
            model_name='bdivcandidate',
            name='roll_no',
        ),
        migrations.RemoveField(
            model_name='bdivregistration',
            name='roll_no',
        ),
        migrations.AlterField(
            model_name='adivcandidate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bdivcandidate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
