# Generated by Django 4.1.1 on 2022-10-09 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0010_remove_adivcandidate_roll_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adivregistration',
            name='div',
        ),
        migrations.RemoveField(
            model_name='bdivregistration',
            name='div',
        ),
    ]
