# Generated by Django 4.1.1 on 2022-10-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0011_remove_adivregistration_div_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADivPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Elections_for', models.TextField(max_length=30, null=True)),
                ('candidate_1', models.CharField(max_length=30, null=True)),
                ('candidate_2', models.CharField(max_length=30, null=True)),
                ('candidate_3', models.CharField(max_length=30, null=True)),
                ('candidate_1_count', models.IntegerField(default=0)),
                ('candidate_2_count', models.IntegerField(default=0)),
                ('candidate_3_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='ADivCandidate',
        ),
    ]
