# Generated by Django 4.1.1 on 2022-10-09 15:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0013_bdivpoll_delete_bdivcandidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adivpoll',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bdivpoll',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
