# Generated by Django 4.1.1 on 2022-10-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0014_alter_adivpoll_id_alter_bdivpoll_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adivpoll',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bdivpoll',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
