# Generated by Django 4.1.3 on 2022-11-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0015_alter_adivpoll_id_alter_bdivpoll_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adivregistration',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adivregistration',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
